// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.protobuf

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	test.protobuf

It has these top-level messages:
	OffsetP2PMsg
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the protobuf package it is being compiled against.
// A compilation error at this line likely means your copy of the
// protobuf package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the protobuf package

type OffsetP2PMsg struct {
	SourceUID int64  `protobuf:"varint,1,opt,name=sourceUID" json:"sourceUID,omitempty"`
	TargetUID int64  `protobuf:"varint,2,opt,name=targetUID" json:"targetUID,omitempty"`
	MsgID     string `protobuf:"bytes,3,opt,name=msgID" json:"msgID,omitempty"`
	Msg       string `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
}

func (m *OffsetP2PMsg) Reset()                    { *m = OffsetP2PMsg{} }
func (m *OffsetP2PMsg) String() string            { return proto.CompactTextString(m) }
func (*OffsetP2PMsg) ProtoMessage()               {}
func (*OffsetP2PMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OffsetP2PMsg) GetSourceUID() int64 {
	if m != nil {
		return m.SourceUID
	}
	return 0
}

func (m *OffsetP2PMsg) GetTargetUID() int64 {
	if m != nil {
		return m.TargetUID
	}
	return 0
}

func (m *OffsetP2PMsg) GetMsgID() string {
	if m != nil {
		return m.MsgID
	}
	return ""
}

func (m *OffsetP2PMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*OffsetP2PMsg)(nil), "main.offsetP2PMsg")
}

func init() { proto.RegisterFile("test.protobuf", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0x2a, 0xe2, 0xe2,
	0xc9, 0x4f, 0x4b, 0x2b, 0x4e, 0x2d, 0x09, 0x30, 0x0a, 0xf0, 0x2d, 0x4e, 0x17, 0x92, 0xe1, 0xe2,
	0x2c, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x0d, 0xf5, 0x74, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e,
	0x42, 0x08, 0x80, 0x64, 0x4b, 0x12, 0x8b, 0xd2, 0x53, 0x4b, 0x40, 0xb2, 0x4c, 0x10, 0x59, 0xb8,
	0x80, 0x90, 0x08, 0x17, 0x6b, 0x6e, 0x71, 0xba, 0xa7, 0x8b, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x84, 0x23, 0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0x02, 0x16, 0x03, 0x31, 0x93,
	0xd8, 0xc0, 0x0e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xb4, 0xfe, 0x5f, 0x8e, 0x00,
	0x00, 0x00,
}
